name: India Current Affairs Auto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # har 6 ghante

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install node-fetch xml2js

      - name: Run builder
        run: node build.js

      - name: Commit data
        run: |
          git config user.name "engine-bot"
          git config user.email "bot@engine.ai"
          git add data.json
          git commit -m "auto update current affairs" || echo "no changes"
          git push
